### ISSUE TITLE
Rack dependency version prevents usage with Rails 4

### ISSUE THREAD

**Issue by KieranP** [janko-m/tus-ruby-server#1]
Was about to use this but then ran into bundler conflict.

Rails 4.2.7.1 has rack dependency of "~> 1.6".

tus-ruby-server has rack dependency of "~> 2.0"

However from what I could see, this gems other dependency, roda, doesn't require such a recent version. 

Would be good to get this gems rack version decreased so it works with Rails 4.

**Comment by CloakedAlien** [comment]
I too have, sort of, this problem. I would like to evaluate it in a larger project. But due to several dependencies we're stuck at rack 1.5.2.

I think it's actionpack 4.0.0 that's keeping us down to such a specific version. Actionpack 4.2.0 could possibly let us move up to rack 1.6, but 2.0 is pretty much not worth the hassle =/

And I'm not sure how feasible an actionpack update is at this time either.

**Comment by KieranP** [comment]
I downgraded the rack dependency in a fork and used that. The majority of things work fine. The only thing that doesn't is `GET /files/:uid` calls because the older/newer versions of rack take a different set of arguments for the same method. But I don't do file serving using the URL anyway, so that worked for me. Would still be good to support both versions of rack though.

**Comment by janko-m** [comment]
For some reason I haven't been "watching" my own project, so I didn't get a notification for this issue 😛

Yes, definitely, I agree tus-ruby-server should support Rack < 2. The only reason for this constraint was that `Rack::File` has a different API, but I didn't realize that older versions of Rails have the Rack constraint. And it's not difficult to support both, [Roda did it easily](https://github.com/jeremyevans/roda/blob/962f944d5877513ca13c5fc7bb9be7ef9c3740c4/lib/roda/plugins/public.rb#L97-L110).

I'll work on Rack 1.x support as soon as I find time.
