### ISSUE TITLE
Mounting multiple Tus::Server instances with different storage adapters

### ISSUE THREAD

**Issue by Aupajo** [janko-m/tus-ruby-server#6]
I'd like to be able to do something like the following in Rack:

```ruby
map '/uploads/s3' do
  run Tus::Server, storage: Tus::Storage::S3.new(...)
end

map '/uploads/filesystem' do
  run Tus::Server, storage: Tus::Storage::Filesystem.new(...)
end
```

I've been digging through the Roda internals, and as far as I can make out, this isn't possible because [`opts` is stored against the class](https://github.com/jeremyevans/roda/blob/master/lib/roda.rb#L151).

I managed to work around the limitation by writing some middleware which injects the intended storage destination into the `Upload-Metadata` header and then implementing a custom storage adapter whose behaviour depends which storage destination was specified in the metadata. Workable, but it would have been a lot simpler to do something like this ☝️ instead.

Is there a way to do what I've sketched out above that I could persue? I'm not well-versed in Roda. From my reading, it might be possible for `Tus::Server` to implement its own [`Roda::Base::InstanceMethods#opts`](https://github.com/jeremyevans/roda/blob/master/lib/roda.rb#L280-L282) which would open the door to instance-level configuration.

**Comment by janko-m** [comment]
Yes, `Tus::Server.opts` is a class-level configuration. It wouldn't be possible to make an instance-level configuration and instantiate `Tus::Server`, because Roda is designed in a way that for every request a new instance of `Tus::Server` is made to handle it. So you need to pass `Tus::Server` as a class. Also, as far as I know, the `run` Rack method doesn't accept additional arguments.

However, `Roda.opts` has a nice feature that, if you subclass the `Roda` class, the subclass makes a copy of `Roda.opts`, which enables proper inheritance. That means you can solve your problem by creating subclasses of `Tus::Server`:

```rb
class S3TusServer < Tus::Server
  opts[:storage] = Tus::Storage::S3.new(...)
end

class FilesystemTusServer < Tus::Server
  opts[:storage] = Tus::Storage::Filesystem.new(...)
end

map '/uploads/s3' do
  run S3TusServer
end

map '/uploads/filesystem' do
  run FilesystemTusServer
end
```

**Comment by Aupajo** [comment]
@janko-m That makes sense! Thanks.
