### ISSUE TITLE
tus server on rails 

### ISSUE THREAD

**Issue by floodico** [janko-m/tus-ruby-server#7]
Hello!
I'm going to use your tus-ruby-server gem in my rails app. Do i need to use goliath-rack_proxy in rails?

**Comment by janko-m** [comment]
See the "Other web servers" section in the README:

> ## Other web servers
> 
> It's perfectly feasible to run tus-ruby-server on web servers other than Goliath or Unicorn (even necessary if you want to run it inside another app). Just keep in mind that most other web servers don't support request streaming, which means that tus-ruby-server will be able to start processing upload requess only once the whole request body has been received. Additionally, incomplete upload requests won't be forwarded to tus-ruby-server, so in order for resumable upload to be possible the client needs to send data in multiple upload requests (which can then be retried individually).

I realized now I could have explained it in a way that's directly actionable. Here it is:

Unless you're using Goliath, or Unicorn with Nginx buffering _disabled_, you'll have to:

* Instruct your JS library (Uppy) to split the upload into chunks, which you should be able to do by specifying the `chunkSize` option to Uppy (`5 * 1024 * 1024` = 5MB is good because it will work with tus-ruby-server's S3 storage). By default tus-js-client (which Uppy uses) will send a single upload request, which if the connection broke would never even reach tus-ruby-server (because Nginx will not forward it), which means you wouldn't be able to achieve resumable uploads.
* Be vary of your disk space usage, because if you're using Puma, the uploaded data will be saved onto filesystem. Though you'll probably need to worry about that only if the traffic increases.
* Be aware that the progress bar for the user might halt for a moment after each 5MB chunk is uploaded, because it needs to wait for tus-ruby-server to save uploaded data to its storage. In Goliath scenario the file is being saved *while* it's being uploaded, so there is no such delay.

With these things in mind, you can safely mount tus-ruby-server inside your Ruby app. You can either mount it in your `config.ru`:

```rb
# config.ru
require "tus/server"

map "/files" do
  run Tus::Server
end

run YourApp
```

or in `config/routes.rb`:

```rb
# config/initializers/tus_server.rb

require "tus/server"

# any tus-ruby-server configuration you want to put in here
```
```rb
# config/routes.rb
Rails.application.routes.draw do
  # ...
  mount Tus::Server => "/files"
end
```
